name = "Crowpack Expert"
author = "crow-maki"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0c018a6470cbcc00f396b5e7aed95576d4f9c9d2bbac4d8d2a80881c0bdc5dcf"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.100"
